FROM nginx

#COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html  /usr/share/nginx/html

#ENV NGINX_VERSION=1.2
ENV MY_NAME=Vitalii 
COPY entrypoint.sh entrypoint.sh
ENTRYPOINT ["sh", "entrypoint.sh"]

